@startuml
!define primary_key(x) <b><u>x</u></b>
!define foreign_key(x) <color:blue>x</color>
class Member {
    name
    points
    balance
}
class Player {
    name
    cost
    base
    team
    country
    type
    score
}

class PlayerInstance {
    primary_key(number)
    foreign_key(player)
    foreign_key(member)
    status
    price
}
note right
    status can be Available, Purchased or Bidding
    Only one playerInstance can have a Bidding status
end note


class Bid {
    primary_key(id)
    foreign_key(member)
    foreign_key(playerInstance)
    bidDate
    amount
}

Player "1" ---> "2" PlayerInstance::player : can have
Member "1" ---> "Many" PlayerInstance::member : can own
Member "1" ---> "Many" Bid::member: can make
PlayerInstance "1" ---> "Many" Bid::playerInstanceNumber : can have
@enduml