# Generated by Django 2.1.5 on 2019-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
