# Generated by Django 2.1.5 on 2019-04-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0004_auto_20190404_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.TextField(default='name', max_length=100),
        ),
    ]
