# Generated by Django 2.1.5 on 2019-04-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0005_auto_20190404_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-points'], 'permissions': (('auctioneer', 'Auctioneer'), ('can_play_ipl2019', 'Can play IPL 2019'))},
        ),
    ]
