# Generated by Django 2.1.5 on 2019-04-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0007_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
