# Generated by Django 2.1.5 on 2019-04-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0008_auto_20190405_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Purchased', 'Purchased'), ('Bidding', 'Bidding')], default='Available', max_length=10)),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipl2019.Member')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl2019.Player')),
            ],
        ),
    ]
