# Generated by Django 2.1.5 on 2019-04-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0009_playerinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinstance',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playerinstances', to='ipl2019.Member'),
        ),
        migrations.AlterField(
            model_name='playerinstance',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerinstances', to='ipl2019.Player'),
        ),
    ]
