# Generated by Django 2.1.5 on 2019-04-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0010_auto_20190408_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('auctioneer', 'Auctioneer'), ('can_play_ipl2019', 'Can play IPL 2019'))},
        ),
        migrations.RemoveField(
            model_name='member',
            name='points',
        ),
    ]
