# Generated by Django 2.1.5 on 2019-04-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0011_auto_20190408_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='ipl2019.Member')),
                ('player_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='ipl2019.PlayerInstance')),
            ],
        ),
    ]
