# Generated by Django 2.1.5 on 2019-04-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0013_auto_20190409_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='base',
            new_name='iplbase',
        ),
    ]
