# Generated by Django 2.1.5 on 2019-04-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0014_auto_20190411_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bgcolor',
            field=models.TextField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='color',
            field=models.TextField(default='black', max_length=20),
        ),
    ]
