# Generated by Django 2.1.5 on 2019-04-16 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0017_auto_20190416_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatch',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='ipl2019.Match'),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_matches', to='ipl2019.Team'),
        ),
    ]
