# Generated by Django 2.1.5 on 2019-04-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0018_auto_20190416_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
