# Generated by Django 2.1.5 on 2019-04-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0019_team_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='teamid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='ipl2019.Team'),
        ),
    ]
