# Generated by Django 2.1.5 on 2019-04-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0020_player_teamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
