# Generated by Django 2.1.5 on 2019-04-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2019', '0021_remove_player_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='teamid',
            new_name='team',
        ),
    ]
